---
title: "2018-10-24"
author: "陳盈蓁"
date: "10/24/2018"
output: html_document
---


```{r}
library(lubridate)
library(stringr)
library(googlesheets)
```



```{r}
install.packages('googlesheets')
library(googlesheets)
```

```{r}
googlesheets::gs_auth()
gs_auth(new_user = TRUE)
```

```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```


```{r}
aa <- (classSurvey$性別 == "男")

bb <- (classSurvey$本學期學分數 > 20)

cc <- (classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 20)
```

#StuDF practice
```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50),
  stringsAsFactors = F
  )
StuDF 
```

```{r}
names(StuDF) 
colnames(StuDF)
```

```{r}
rownames(StuDF)
```


```{r}
rownames(classSurvey)
```

```{r}
StuDF[1,2]
StuDF[,2]
StuDF[1,]
```

```{r}
StuDF[c(1,4),]
```

```{r}
StuDF[c(1,4),c(2,3)]
```

```{r}
StuDF[c(1:3,5),]
```

```{r}
StuDF[c(1,4),]
```

```{r}
StuDF[-c(1,4),]
```

```{r}
StuDF
StuDF[c(T,F,F,F,F),c(F,T,F)]
StuDF[c(T,F,F,T,F),]
```

```{r}
a<-c(T,T,F,F,T,F,F)
sum(a)
```

```{r}
StuDF[c(T,F,F,F,F),]
```

```{r}
StuDF[1,]
```

```{r}
StuDF[c(T,F,F,T,F),c(F,T,T,F,F)]
```

```{r}
StuDF[c(1,4),c(2,3)]
```

```{r}
(StuDF$score >= 80)
(StuDF$name == "小新")
```

```{r}
StuDF[StuDF$score >= 80,2]
StuDF[StuDF$name == "小新",3]
```

```{r}
library(stringr)
classSurvey[classSurvey$性別 == "男" & 
    classSurvey$本學期學分數>26,3]
```

```{r}
library(stringr)
str_sub(classSurvey$居住地行政區,1,2)
classSurvey[str_sub(classSurvey$居住地行政區,1,2) =="新北",3]
```

```{r}
library(stringr)
str_sub(classSurvey$居住地行政區,1,2)
classSurvey[str_sub(classSurvey$居住地行政區,1,2) =="台北",3]
```

```{r}
StuDF$StuID
StuDF[,c("StuID")]
StuDF$name
StuDF[,c("name")]
```

```{r}
StuDF[,c("StuID","name")]

## 無法用$一次取兩個元素
# StuDF$c("StuID","name")
```

```{r}
StuDF[c(1,4),c(2)]
StuDF[,c(2)][c(1,4)]

## the second one is equivalent to 
StuDF[,c(2)] -> aa
aa[c(1,4)] 
```

```{r}
```

