---
title: '2018-12-12'
author: "陳盈蓁"
date: "12/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 %>% as.factor %>% levels -> storageLocations
storageLocations
```

```{r}
i<-1
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
```

##不同館藏地
```{r}
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i
}
```

##不同學院借書量
```{r}
libraryData$學院 %>% as.factor %>% levels -> college
allBorrowCountofcollege <- vector("numeric",length(college))
for(i in c(1:length(college))){
college_i <- college[i]
numericalIndexForcollegeSubsample <- which(libraryData$學院==college_i)
collegeSubsample_i <-libraryData[numericalIndexForcollegeSubsample,]
collegeborrowCount_i <- nrow(collegeSubsample_i)
allBorrowCountofcollege[[i]]<- collegeborrowCount_i
}
allBorrowCountofcollege
```

##不同學號借書量
(for(i in c(1:length(studentID))可用for(i in seq_along(studentID)))
```{r}
libraryData$學號 %>% as.factor %>% levels -> studentID
allBorrowCountofeachstudent <- vector("numeric",length(studentID))
for(i in c(1:length(studentID))){
studentID_i <- studentID[i]
numericalIndexForstudentIDSubsample <- which(libraryData$學號==studentID_i)
studentIDSubsample_i <-libraryData[numericalIndexForstudentIDSubsample,]
studentIDborrowCount_i <- nrow(studentIDSubsample_i)
allBorrowCountofeachstudent[[i]]<- studentIDborrowCount_i
}
```
```{r}
libraryData %>%
  group_by(書籍館藏地) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result
result
```


```{r}
libraryData %>%
  mutate(
  學系=str_sub(學號,5,6)
    ##相當於 libraryData$學系 <- str_sub(libraryData$學號,5,6)
  )-> libraryData
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result2
result2
```

```{r}
ymd_hms(libraryData$借閱時間) %>% with_tz(.,tz="Asia/Taipei") -> libraryData$借閱時間
libraryData%>%
  group_by(學號,借閱時間)%>%
  summarise(
    
  )
```

```{r}
libraryData %>%
  mutate(
      借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei")
  ) %>%
  group_by(學號) %>%
  summarise(
    第一次借書=min(借閱時間)
  ) %>%
  ungroup -> result3
result3
```

```{r}
libraryData %>%
  filter(入學年==102)
```

